### PR TITLE
Add Prometheus exporter

### PR DESCRIPTION
**Pull request by mpoeter**
This is a simple Foxx service that provides the internal statistics from ArangoDB in the Prometheus format.

### CODE REVIEW

**Comment by OmarAyo** [comment]
Hi @mpoeter 

Many thanks for contributing. We are obliged by law to have a signed scanned copy of a Contributor License Agreement (CLA) to be able to accept pull requests to the official ArangoDB repository - even for such small changes.

We use an Apache 2 CLA for ArangoDB and its companion projects, which can be found here: https://www.arangodb.com/documents/cla.pdf
Just fill in the form, sign and send a scanned copy over to cla@arangodb.com 

Thank you

**Comment by mpoeter** [comment]
Hi @OmarAyo 

I have already signed the CLA back in January. :slightly_smiling_face:

**Comment by OmarAyo** [comment]
Hi @mpoeter,

My apologies - yes we have already your signed CLA.

Thanks

**Comment by pluma** [comment]
Hey @mpoeter, I'm sorry but it seems the PR fell between the cracks somehow.

Are you still interested in merging this? It looks like your repo has been inactive for a while.

**Comment by mpoeter** [comment]
@pluma No problem. Yes, the repo has been inactive. The reason simply is that the exporter does exactly what it is supposed to, so there were no reasons for any updates. :wink: So sure, you can still merge this.

@Simran-B Yes, but back at the time I haven't found any Prometheus exporters for ArangoDB. That's the reason I implemented this one in the first place. And it has been running without problems in our production system ever since. No reason for us to change, at least for now. :slightly_smiling_face:

**Pull request merged**
